### ISSUE TITLE
listS3Buckets fails with 404

### ISSUE THREAD

**Issue by dan-earle** [Nike-Inc/gradle-localstack#20]
**Describe the bug**
After successfully creating a bucket (using CreateS3BucketsTask gradle task) and storing a file in it with my program, when I go to list all buckets I get 404 error:
`Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.
Error:  (Service: Amazon S3; Status Code: 404; Error Code: 404 ; Request ID: null; S3 Extended Request ID: null)
Retrying...
`

**To Reproduce**
Setup file like this:
build.gradle:
`..
// LocalStack Configuration
dockerCompose {
    useComposeFiles = [ 'localstack/docker-compose.yml' ]
}

localstack {
    host = 'localhost'
    port = 4566
    signingRegion = 'eu-west-2'
    springboot {
        profiles = [ 'local' ]
    }
}

task setupS3Bucket(type: CreateS3BucketsTask) {
    buckets = [ 'bucket' ]
}
`
localstack/docker-compose.yml
`
version: '3.5'

services:
  localstack:
    image: localstack/localstack:0.11.3
    ports:
      - '4566:4566'   # LocalStack Edge
    environment:
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
`
Then type:
./gradlew listS3Buckets

**Expected behaviour**
Expect a list of buckets currently setup in the running localstack 

**Versions**
Add library versions to help reproduce the bug.

* Plugin:
* Gradle:
6.6.1
* Docker:
19.03.11
* Docker Compose:
1.25.5
* Spring Boot:

**Additional context**
When running with --debug switch on gradle, below is a snippet of the log:
`...
10:06:14.714 [DEBUG] [com.amazonaws.services.s3.S3CredentialsProviderChain] No credentials available; falling back to anonymous access
10:06:14.717 [DEBUG] [com.amazonaws.request] Sending Request: GET http://localhost:4566 / Headers: (User-Agent: aws-sdk-java/1.11.447 Linux/5.4.0-56-generic OpenJDK_64-Bit_Server_VM/11.0.9.1+1-Ubuntu-0ubuntu1.20.04 java/11.0.9.1 groovy/2.5.4 kotlin/1.3.41, amz-sdk-invocation-id: 80ea0a3d-f585-fcbc-8b27-1e141ed27c2e, Content-Type: application/octet-stream, ) 
10:06:14.717 [DEBUG] [com.amazonaws.auth.AWSCredentialsProviderChain] Unable to load credentials from EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
10:06:14.721 [DEBUG] [com.amazonaws.auth.AWSCredentialsProviderChain] Unable to load credentials from SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey)
10:06:14.721 [DEBUG] [com.amazonaws.auth.AWSCredentialsProviderChain] Unable to load credentials from com.amazonaws.auth.profile.ProfileCredentialsProvider@575c3086: No AWS profile named 'default'
10:06:15.771 [DEBUG] [com.amazonaws.auth.AWSCredentialsProviderChain] Unable to load credentials from com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@51fcaa1b: Unable to load credentials from service endpoint
10:06:15.771 [DEBUG] [com.amazonaws.services.s3.S3CredentialsProviderChain] No credentials available; falling back to anonymous access
10:06:15.789 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: default
10:06:15.796 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
10:06:15.797 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection request: [route: {}->http://localhost:4566][total available: 0; route allocated: 0 of 50; total allocated: 0 of 50]
10:06:15.807 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection leased: [id: 0][route: {}->http://localhost:4566][total available: 0; route allocated: 1 of 50; total allocated: 1 of 50]
10:06:15.809 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Opening connection {}->http://localhost:4566
10:06:15.811 [DEBUG] [org.apache.http.impl.conn.DefaultHttpClientConnectionOperator] Connecting to localhost/127.0.0.1:4566
10:06:15.812 [DEBUG] [org.apache.http.impl.conn.DefaultHttpClientConnectionOperator] Connection established 127.0.0.1:42034<->127.0.0.1:4566
10:06:15.812 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-0: set socket timeout to 50000
10:06:15.812 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Executing request GET / HTTP/1.1
10:06:15.812 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Target auth state: UNCHALLENGED
10:06:15.813 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Proxy auth state: UNCHALLENGED
10:06:15.823 [DEBUG] [org.apache.http.impl.conn.DefaultManagedHttpClientConnection] http-outgoing-0: Close connection
10:06:15.823 [DEBUG] [org.apache.http.impl.execchain.MainClientExec] Connection discarded
10:06:15.823 [DEBUG] [org.apache.http.impl.conn.PoolingHttpClientConnectionManager] Connection released: [id: 0][route: {}->http://localhost:4566][total available: 0; route allocated: 0 of 50; total allocated: 0 of 50]
10:06:15.862 [DEBUG] [com.amazonaws.services.s3.internal.S3ErrorResponseHandler] Failed in parsing the error response : {"status": "running"}
javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:652)
        at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.createException(S3ErrorResponseHandler.java:115)
        at com.amazonaws.services.s3.internal.S3ErrorResponseHandler.handle(S3ErrorResponseHandler.java:64)
...`

**Comment by gregwhitaker** [comment]
Based on the error it appears that you do not have a `[default]` aws profile in your `.aws/credentials` file. Currently, the plugin requires this and should be documented. There is the possibility we could add the ability to set a profile name during configuration to get around this. The whole profile thing is kinda moot with LocalStack anyway as it doesn't actually do anything with the keys and accepts whatever you give it. However, the java sdk under the covers still wants to be able to retrieve the keys from the expected places and send them.

Can you please verify that you have a default profile setup?

**Comment by gregwhitaker** [comment]
Closing as there was no response.
